# jekyll config

# blog name
name: "devedge"

author:
  github: "devedge"
  stackoverflow:
  linkedin:
  medium:
  email:

copyright:
  year: 2021
  name: devedge

# URL
url: "https://devedge.github.io"
# url: "http://localhost:4000"

timezone: America/New_York
permalink: /:year-:month-:day/:title/

# Pagination
paginate: 5
paginate_path: /page:num/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Navigation
nav:
  - name: "About"
    url: "/about"
  - name: "Archive"
    url: "/archive"
  - name: "Tags"
    url: "/tags"
  - name: "Github"
    url: "https://github.com/devedge"

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Scopes
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

gems:
  - jekyll-paginate
  - jekyll-admin

plugins: [jekyll-paginate]

exclude: [vendor]
